version: '3.8'
services:

  backend:
    build:
      context: .
    # ports:
    #   - "8080:8080"
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: always    