version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always
